### ISSUE TITLE
Metadata for esbServerName does not use COMPUTERNAME or HOSTNAME environment variables

### ISSUE THREAD

**Issue by klindklind** [Aino-io/agent-wso2-esb#19]
Even though you set COMPUTERNAME or HOSTNAME environment variable in server instance running your ESB, the metadata called "esbServerName" will be set with value "localhost".

Check the source code:
AinoMediatorFactory.getHostName(InputStream axis2ConfigInputStream)

NOTE! getInetHostName() will most probably get you a "localhost" or possibly throw an exception.

**Comment by esaheikkinen** [comment]
As of release 1.2.3 the logic of getting host name for esbServerName metadata is as follows:

1. COMPUTERNAME environment variable (if specified)
2. HOSTNAME environment variable (if specified)
3. SynapseConfig.ServerName parameter in axis2.xml configuration file (if specified)
4. finally use InetAddress.getLocalHost().getHostName()
