### ISSUE TITLE
Aino config ainoLoggerService enabled = false causes ESB not to start properly

### ISSUE THREAD

**Issue by kallja** [Aino-io/agent-wso2-esb#22]
When disabling Aino Logger Service in the `ainoLogMediatorConfig.xml` file (`enabled = false` or remove enabled attribute), ESB fails to start with attached stacktrace.

ZIP has stacktrace and config file to reproduce.

Relevant application entry is defined.

Error message from aino:
`io.aino.agents.core.config.InvalidAgentConfigException: application with key 'esb' must be configured.`
[aino-issue.zip](https://github.com/Aino-io/agent-wso2-esb/files/895668/aino-issue.zip)

**Comment by esaheikkinen** [comment]
Fixed in release 1.2.3
